version: '3'

services:
        dbos1:
                image: mysql:5.7
                volumes:
                        - mydb2:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: Raushan@root
                        MYSQL_USER: raushan
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: db2

        wpos1:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - dbos1                                  
                ports:
                        - 8082:80
                environment:
                        WORDPRESS_DB_HOST: dbos1
                        WORDPRESS_DB_USER: raushan        
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: db2
                volumes:
                        - wp2:/var/www/html
volumes:
        wp2:
        mydb2:
